version: 2.1
orbs:
  php: circleci/php@1.1.0
jobs:
  lint-and-test:
    docker:
      - image: cimg/php:8.3.4
    steps:
      - checkout
      - php/install-composer:
          install-version: '2.7.2'
      - php/install-packages:
          cache-key: 'composer.json'
      - run:
          name: Lint
          command: composer lint
      - run:
          name: Test
          command: composer test
workflows:
  lint-and-test:
    jobs:
      - lint-and-test
